'use strict'

module.exports = {
  DONATION_FROM_GUEST_TO_SERVICE: 'DONATION_FROM_GUEST_TO_SERVICE',
  DONATION_FROM_USER_TO_SERVICE: 'DONATION_FROM_USER_TO_SERVICE',
  DONATION_FROM_GUEST_TO_POST_AUTHOR: 'DONATION_FROM_GUEST_TO_POST_AUTHOR',
  DONATION_FROM_USER_TO_POST_AUTHOR: 'DONATION_FROM_USER_TO_POST_AUTHOR',
  PRICING_PLAN_FROM_USER_TO_SERVICE: 'PRICING_PLAN_FROM_USER_TO_SERVICE',
}
